### ISSUE TITLE
PlagiarismChecker.Setup project cannot be loaded

### ISSUE THREAD

**Issue by CBenghi** [dipongkor/PlagiarismChecker#1]
Hello,

I'm trying to look at the code and I'm encountering issues in loading one of the projects.

![image](https://user-images.githubusercontent.com/5476273/76226781-a5e4d600-621e-11ea-8e04-ad1a4cd0b5ed.png)

Can you help me understand how to solve that?

Edit: I'm using:
```
Microsoft Visual Studio Community 2019 Preview
Version 16.5.0 Preview 5.0
```

**Comment by dipongkor** [comment]
Sorry for not mentioning it in the README. Please install the following extension

https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects

**Comment by dipongkor** [comment]
I have added this information in the README.
