### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by CBenghi** [dipongkor/PlagiarismChecker#3]
The solution seems to use a dependency that is marked as deprecated.

see: https://www.nuget.org/packages/iTextSharp/

```PLEASE NOTE: iTextSharp is EOL, and has been replaced by iText 7. Only security fixes will be added```

If you intend to continue pursuing publication on Joss this would need to be fixed.

**Comment by dipongkor** [comment]
Thanks for your feedback. I have removed iTextSharp and added iText 7.
